name: feathers
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth:
  google_sign_in:
  cloud_firestore:
  google_maps_flutter:
  location: ^3.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mapview_assets/top.png
    - assets/mapview_assets/bottom.png
    - assets/mapview_assets/search.png
    - assets/mapview_assets/menu.png
    - assets/mapview_assets/wing.png
    - assets/mapview_assets/pin.png
    - assets/mapview_assets/tree.png
    - assets/mapview_assets/user.png
    - assets/mapview_assets/wing.png
#    - assets/login_assets/button_border.png
#    - assets/login_assets/Breathing_button.gif
#    - assets/login_assets/flower_gif.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Gibson
      fonts:
        - asset: assets/fonts/gibson-bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
